---
- name: Install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present
  tags: php

- name: Install php72-php-fpm and deps
  yum: name={{ item }} state=present enablerepo=epel,remi
  with_items:
    - php72
    - php72-php-cli
    - php72-php-fpm
    - php72-php-intl
    - php72-php-pdo
    - php72-php-mbstring
    - php72-php-opcache
    - php72-php-pecl-zip
    - php72-php-xml
    - php72-php-pecl-xdebug
  tags: php

- name: Start php72-php-fpm Service
  service: name=php72-php-fpm state=started enabled=yes

- name: Disable default pool
  command: mv /etc/opt/remi/php72/php-fpm.d/www.conf /etc/opt/remi/php72/php-fpm.d/www.disabled creates=/etc/opt/remi/php72/php-fpm.d/www.disabled
  tags: php

- name: Copy php-fpm configuration
  template: src=nginx.conf dest=/etc/opt/remi/php72/php-fpm.d/
  notify: restart php-fpm
  tags: php
