---
- name: be sure mysql is installed
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present
  tags: mysqld

- name: be sure mysql-server is installed
  yum: name=mysql-server state=present
  tags: mysqld

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"
  tags: mysqld

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  tags: mysqld
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
  tags: mysqld
