---
- name: Install nginx
  yum: name=nginx state=present
  tags: httpd

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags: httpd

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  tags: httpd

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes
  tags: httpd

- name: http service state
  service: name=nginx state=restarted enabled=yes
  tags: httpd
